{% set name = "ansi" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansi-{{ version }}.tar.gz
  sha256: 7e59108922259e03c54e4d93fc611bba0e756513086849708b86b6c80f8d4cd4

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6
    - typing-extensions >=3.6.4

test:
  imports:
    - ansi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tehmaze/ansi/
  summary: ANSI cursor movement and graphics
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - BastianZim
